// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement.Data;

#nullable disable

namespace UserManagement.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserManagement.Data.Entities.User", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Forename")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Surname")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Users");

                b.HasData(
                    new
                    {
                        Id = 1L,
                        Forename = "Peter",
                        Surname = "Loew",
                        Email = "ploew@example.com",
                        IsActive = true
                    },
                    new
                    {
                        Id = 2L,
                        Forename = "Benjamin Franklin",
                        Surname = "Gates",
                        Email = "bfgates@example.com",
                        IsActive = true
                    },
                    new
                    {
                        Id = 3L,
                        Forename = "Castor",
                        Surname = "Troy",
                        Email = "ctroy@example.com",
                        IsActive = false
                    },
                    new
                    {
                        Id = 4L,
                        Forename = "Memphis",
                        Surname = "Raines",
                        Email = "mraines@example.com",
                        IsActive = true
                    },
                    new
                    {
                        Id = 5L,
                        Forename = "Stanley",
                        Surname = "Goodspeed",
                        Email = "sgodspeed@example.com",
                        IsActive = true
                    },
                    new
                    {
                        Id = 6L,
                        Forename = "H.I.",
                        Surname = "McDunnough",
                        Email = "himcdunnough@example.com",
                        IsActive = true
                    },
                    new
                    {
                        Id = 7L,
                        Forename = "Cameron",
                        Surname = "Poe",
                        Email = "cpoe@example.com",
                        IsActive = false
                    },
                    new
                    {
                        Id = 8L,
                        Forename = "Edward",
                        Surname = "Malus",
                        Email = "emalus@example.com",
                        IsActive = false
                    },
                    new
                    {
                        Id = 9L,
                        Forename = "Damon",
                        Surname = "Macready",
                        Email = "dmacready@example.com",
                        IsActive = false
                    },
                    new
                    {
                        Id = 10L,
                        Forename = "Johnny",
                        Surname = "Blaze",
                        Email = "jblaze@example.com",
                        IsActive = true
                    },
                    new
                    {
                        Id = 11L,
                        Forename = "Robin",
                        Surname = "Feld",
                        Email = "rfeld@example.com",
                        IsActive = true
                    });
            });
#pragma warning restore 612, 618
        }
    }
}
